### ISSUE TITLE
Generic Error when uploading PDFs

### ISSUE THREAD

**Issue by osaa-mantonio** [ilovepdf/ilovepdf-wp#17]
Every time we upload a PDF the following error pops up. The only info provided is the filename and the number "1". 
![ilovepdf-error_media-library](https://github.com/ilovepdf/ilovepdf-wp/assets/55147691/de1d10fe-f131-4bd1-aec4-7bb22920c0a7)

However, the file successfully uploads and shows in the Media Library after refreshing the page, but there are several users uploading documents so the error has been quite a nuisance. I enabled debugging hoping for a better explanation and was provided with the following
![ilovepdf-error_debug-log](https://github.com/ilovepdf/ilovepdf-wp/assets/55147691/58b044d4-a659-4338-a69e-90401305a7d8)

`[24-Oct-2023 11:34:46 UTC] PHP Deprecated:  Optional parameter $code declared before required parameter $response is implicitly treated as a required parameter in /var/www/********/wp-content/plugins/ilovepdf/lib/ilovepdf-php-master/src/Exceptions/ExtendedException.php on line 20`

I have no idea if any of this is even related, but it would be nice to clear this up! Any feedback would be appreciated. The errors do not happen if the plugin is disabled.

Wordpress - 6.3.2
PHP - 8.1.24
iLovePDF - 2.0.0

**Comment by diegocrombie** [comment]
Fixed in version 2.0.1 thanks
